// Generated by scripts/import-thumbnails.mjs. Re-run it to change; don't edit by hand.

/** Video thumbnails, keyed by video number. */
export const lessonThumbs: Record<string, string> = {
  "0.1": "/thumbs/the-prod/0-1.jpg",
  "0.2": "/thumbs/the-prod/0-2.jpg",
  "1.1": "/thumbs/the-prod/1-1.jpg",
  "1.2": "/thumbs/the-prod/1-2.jpg",
  "2.1": "/thumbs/the-prod/2-1.jpg",
  "2.2": "/thumbs/the-prod/2-2.jpg",
  "2.3": "/thumbs/the-prod/2-3.jpg",
  "2.4": "/thumbs/the-prod/2-4.jpg",
  "2.5": "/thumbs/the-prod/2-5.jpg",
  "2.6": "/thumbs/the-prod/2-6.jpg",
  "2.7": "/thumbs/the-prod/2-7.jpg",
  "2.8": "/thumbs/the-prod/2-8.jpg",
  "3.1": "/thumbs/the-prod/3-1.jpg",
  "3.2": "/thumbs/the-prod/3-2.jpg",
  "4.1": "/thumbs/the-prod/4-1.jpg",
  "4.2": "/thumbs/the-prod/4-2.jpg",
  "4.3": "/thumbs/the-prod/4-3.jpg",
  "4.4": "/thumbs/the-prod/4-4.jpg",
  "4.5": "/thumbs/the-prod/4-5.jpg",
  "5.1": "/thumbs/the-prod/5-1.jpg",
  "5.2": "/thumbs/the-prod/5-2.jpg",
  "5.3": "/thumbs/the-prod/5-3.jpg",
  "5.4": "/thumbs/the-prod/5-4.jpg",
  "6.1": "/thumbs/the-prod/6-1.jpg",
  "6.2": "/thumbs/the-prod/6-2.jpg",
  "6.3": "/thumbs/the-prod/6-3.jpg",
  "7.1": "/thumbs/the-prod/7-1.jpg",
  "7.2": "/thumbs/the-prod/7-2.jpg",
  "7.3": "/thumbs/the-prod/7-3.jpg",
  "7.4": "/thumbs/the-prod/7-4.jpg",
  "8.1": "/thumbs/the-prod/8-1.jpg"
};

/** Day covers, keyed by module id. */
export const dayCovers: Record<string, string> = {
  "day-1": "/thumbs/the-prod/day-1.jpg",
  "day-2": "/thumbs/the-prod/day-2.jpg",
  "day-3": "/thumbs/the-prod/day-3.jpg",
  "day-4": "/thumbs/the-prod/day-4.jpg",
  "day-5": "/thumbs/the-prod/day-5.jpg",
  "day-6": "/thumbs/the-prod/day-6.jpg",
  "day-7": "/thumbs/the-prod/day-7.jpg",
  "welcome": "/thumbs/the-prod/welcome.jpg",
  "wrap-up": "/thumbs/the-prod/wrap-up.jpg"
};

/** Course card and page cover. */
export const courseCover: string | null = null;
