// Generated by scripts/import-thumbnails.mjs. Re-run it to change; don't edit by hand.

/** Video thumbnails, keyed by video number. */
export const lessonThumbs: Record<string, string> = {};

/** Day covers, keyed by module id. */
export const dayCovers: Record<string, string> = {};

/** Course card and page cover. */
export const courseCover: string | null = null;
